### ISSUE TITLE
你好请教一下为啥会这样啊，索引超范围？

### ISSUE THREAD

**Issue by AcAugus** [princelai/auto_enaea#1]

**Comment by AcAugus** [comment]
Traceback (most recent call last):
  File "main.py", line 366, in <module>
    study.start()
  File "main.py", line 85, in start
    self.create_overall_task()
  File "main.py", line 190, in create_overall_task
    project_name, project_progress = self.get_project_info(j, get_name=True)
  File "main.py", line 151, in get_project_info
    project_title = self.driver.find_element_by_xpath('//*[@id="guide-sub-title"
]/a').text.split('•')[1]
IndexError: list index out of range
