### ISSUE TITLE
您好 我们遇到了一个问题

### ISSUE THREAD

**Issue by UpbeatDylan** [princelai/auto_enaea#2]
使用这条命令后 登陆成功 但是报错了 部分如下  python main.py -u username -p password 麻烦您了
[1107/204500.615:INFO:CONSOLE(509)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://fs-im-kefu.7moor-fs1.com/im/f5f042b0-6cdc-11ea-b9e9-11f72acca0b4/2
020-06-05%2011:44:42/1591328682791/m7AllQuote.js (509)
Traceback (most recent call last):
  File "main.py", line 366, in <module>
    study.start()
  File "main.py", line 85, in start
    self.create_overall_task()
  File "main.py", line 190, in create_overall_task
    project_name, project_progress = self.get_project_info(j, get_name=True)
  File "main.py", line 151, in get_project_info
    project_title = self.driver.find_element_by_xpath('//*[@id="guide-sub-title"]/a').text.split('•')[1]
IndexError: list index out of range

**Comment by princelai** [comment]
chrome driver安装了吗，如果安装了就是他们页面元素变了，需要从新定位
